version: '3'
services:
  efserver:
    image: "electricflow/efserver:latest"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    container_name: efserver
    hostname: "efserver"
    tty: true
  build:
    hostname: "svnserver"
    container_name: svnserver
    tty: true
    context: .
    dockerfile: Dockerfile
    ports:
      - "3690:3690"
