version: '3'
services:
  efserver:
    container_name: efserver
    hostname: "efserver"
    build:
      context: .
      dockerfile: efserver.dockerfile
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    tty: true
  svnserver:
    container_name: svnserver
    hostname: "svnserver"
    build:
      context: .
      dockerfile: svnserver.dockerfile
    ports:
      - "3690:3690"
    tty: true
